'''
389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

https://leetcode.com/problems/find-the-difference/
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        retVal = 0
        for ch in s + t:
            retVal ^= ord(ch)
        return chr(retVal)
